[assembly: System.Reflection.AssemblyVersion("4.2.0.0")]
[assembly: System.Reflection.AssemblyDescription(".NET代码生成器")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Reflection.AssemblyTitle("Business Development Studio 4.0")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyFileVersion("4.2.0")]
[assembly: System.Runtime.InteropServices.Guid("7188ba74-3917-40aa-8100-33cc8870933a")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("版权所有 (C) Flextronics 2009")]
[assembly: System.Reflection.AssemblyProduct("i-Flex Business Suite")]
[assembly: System.Reflection.AssemblyCompany("伟创力塑胶科技（深圳）有限公司")]

